http:
  timeout: "30000"
  port: "8081"

db:
  host: "host name"
  port: "3306"
  user: "user name"
  password: "password"
  database: "db name"

sql:
  insertQuery: "Insert into my_table(product_name,price,rating,review,platform) values (:productName,:price,:rating,:review,:platform);"
  insertErrorQuery: "Insert into error_table(product_name,price,rating,review,platform) values (:productName,:price,:rating,:review,:platform);"
